[project]
drom-version = "0.1"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.10.0"
mode = "binary"
name = "digodoc"
synopsis = "The digodoc project"
version = "0.1.0"
windows-ci = true

# keys that you could also define:
# build-profile = "...build-profile..."
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
This is the description
of the digodoc OCaml project
"""

[drom]
skip = "src/digodoc/main.ml src/digodoc_lib/main.ml src/ez_xml/main.ml"

[dependencies]

[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]
generators = ["ocamllex", "ocamlyacc"]
pack-modules = true
share-dirs = ["share"]
skip-dirs = []


[[package]]
dir = "src/digodoc"

[[package]]
dir = "src/digodoc_lib"

[[package]]
dir = "src/meta_file"

[[package]]
dir = "src/ez_xml"

